### ISSUE TITLE
Could not set text to MFTextField programatically.

### ISSUE THREAD

**Issue by arvindrajnaidu** [stephsharp/MaterialTextField#8] opened 2016-08-18 10:50 UTC
Setting a string value for text simply clears the field. Does not do anything.

**Comment by stephsharp** [comment] 2018-06-24 22:20
Hi @arvindrajnaidu, I have been unable to reproduce this bug. I'm closing this issue, but if you're still having problems with this bug please open a new issue with some extra information on how to reproduce. Thanks!

**Closed as completed by stephsharp** 2018-06-24 22:20 UTC
